services:
  web:
    image: node:lts-bookworm-slim
    working_dir: /app
    volumes:
      - ./:/app
    command: >-
      sh -c "npx --yes http-server ./ -p 3000 -c-1"
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token "${CLOUDFLARED_TUNNEL_TOKEN}"
    depends_on:
      - web
    volumes:
      - ./cloudflared/config.yml:/etc/cloudflared/config.yml:ro
      - ${CLOUDFLARED_CREDENTIALS_FILE_HOST:-./cloudflared/tunnel-credentials.json}:${CLOUDFLARED_CREDENTIALS_FILE_CONTAINER:-/etc/cloudflared/tunnel-credentials.json}:ro
    env_file:
      - ./cloudflared/.env
    environment:
      CLOUDFLARED_TUNNEL_TOKEN: ${CLOUDFLARED_TUNNEL_TOKEN:-}
      CLOUDFLARED_TUNNEL_UUID: ${CLOUDFLARED_TUNNEL_UUID:-}
      CLOUDFLARED_CREDENTIALS_FILE_CONTAINER: ${CLOUDFLARED_CREDENTIALS_FILE_CONTAINER:-/etc/cloudflared/tunnel-credentials.json}
    restart: unless-stopped
