# Cloudflared tunnel configuration for dev.chateaufollent.com.au
# Replace the placeholder values with the tunnel UUID and credentials filename
# provided by Cloudflare.

# The UUID of the tunnel created for Lord James Follent's preview environment.
# Populate this via the CLOUDFLARED_TUNNEL_UUID variable stored in a private env file.
tunnel: ${CLOUDFLARED_TUNNEL_UUID}
# This path must match the name of the credentials file saved securely outside the repository
# and injected via docker-compose environment variable expansion.
credentials-file: ${CLOUDFLARED_CREDENTIALS_FILE_CONTAINER}

ingress:
  - hostname: dev.chateaufollent.com.au
    # When developing on Windows Docker Desktop, cloudflared must contact the host via
    # the special DNS name below so traffic escapes the container namespace.
    # If every service runs inside Docker Compose, switch this back to
    # http://web:3000 to stay within the Compose network.
    service: http://host.docker.internal:3000
  - service: http_status:404
